### ISSUE TITLE
tests fail on master at NERSC

### ISSUE THREAD

**Issue by sbailey** [desihub/desiutil#79]
Tests on desiutil master are failing at NERSC (tested on both cori and edison using desimodules/test-master with default desiconda install)
```
source /project/projectdirs/desi/software/desi_environment.sh master
module unload desiutil
git clone https://github.com/desihub/desiutil
cd desiutil
python setup.py test

======================================================================
ERROR: test_start_modules (desiutil.test.test_install.TestInstall)
Test the initialization of the Modules environment.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/global/u2/s/sjbailey/temp/desiutil/py/desiutil/test/test_install.py", line 396, in test_start_modules
    status = self.desiInstall.start_modules()
  File "/global/u2/s/sjbailey/temp/desiutil/py/desiutil/install.py", line 703, in start_modules
    raise DesiInstallException(message)
desiutil.install.DesiInstallException: Could not initialize Modules with MODULESHOME=/fake/module/directory!

======================================================================
FAIL: test_default_nersc_dir (desiutil.test.test_install.TestInstall)
Test determination of the NERSC installation root.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/global/u2/s/sjbailey/temp/desiutil/py/desiutil/test/test_install.py", line 312, in test_default_nersc_dir
    self.assertEqual(nersc_dir, '/global/common/edison/contrib/desi/desiconda/current')
AssertionError: '/global/common/edison/contrib/desi/desiconda/desi' != '/global/common/edison/contrib/desi/desiconda/current'
- /global/common/edison/contrib/desi/desiconda/desi
?                                              ^ ^^
+ /global/common/edison/contrib/desi/desiconda/current
?                                              ^^^^ ^^


======================================================================
FAIL: test_get_options (desiutil.test.test_install.TestInstall)
Test the processing of desiInstall command-line arguments.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/global/u2/s/sjbailey/temp/desiutil/py/desiutil/test/test_install.py", line 105, in test_get_options
    self.assertEqual(options, default_namespace)
AssertionError: Namespace(anaconda='desi', bootstrap=False, config_file='', c[259 chars]alse) != Namespace(anaconda='current', bootstrap=False, config_file=''[262 chars]alse)
```

Note that unlike #78, this is running tests directly on a git checkout instead of a fully installed version, and results in a different set of failures.

**Comment by weaverba137** [comment]
I've fixed the two "FAIL" problems, but I can't reproduce the MODULESHOME error so far.

While fixing this, I've verified that the failures would not affect the normal operation of desiutil (*i.e.* there's no need to rush out a new tag).  The *tests* were not anticipating the case where `$DESICONDA` was already set in the environment.

**Comment by weaverba137** [comment]
The MODULESHOME error is actually a knock-on effect of the failure of another test.  `test_get_options` fails and then doesn't clean up after itself, resulting in an incorrectly set `$MODULESHOME` environment variable.  This should go away now that `test_get_options` is fixed.
